export const menu = [
    { item: "Εσπρεσο φρεντο", price: 3.5, itemQuantity: 1 },
    { item: "Καπουτσινο μονο ", price: 3.5, itemQuantity: 1 },
    { item: "Καπουτσινο διπλο ", price: 3.5, itemQuantity: 1 },
    { item: "καπουτσινο φρεντο", price: 4, itemQuantity: 1 },
    { item: "Ροφηματα", price: 4, itemQuantity: 1 },
    { item: "Χυμος Λακωνια", price: 3.5, itemQuantity: 1 },
    { item: "Κανατα τσαι", price: 7, itemQuantity: 1 },
    { item: "Αναψυκτικο", price: 3, itemQuantity: 1 },
    { item: "Red bull", price: 4, itemQuantity: 1 },
    { item: "Toast", price: 3, itemQuantity: 1 },
    { item: "Αραβικη", price: 4, itemQuantity: 1 },
    { item: "Club Bacon", price: 6, itemQuantity: 1 },
    { item: "Κρασι παραγκα ποτηρι", price: 5, itemQuantity: 1 },
    { item: "Κρασι παραγκα Φιαλη", price: 22, itemQuantity: 1 },
    { item: "Ροζε ποτηρι", price: 5.5, itemQuantity: 1 },
    { item: "Estrella", price: 5, itemQuantity: 1 },
    { item: "Magners", price: 4.5, itemQuantity: 1 },
    { item: "Paulaner", price: 5.5, itemQuantity: 1 },
    { item: "Asashi", price: 5, itemQuantity: 1 },
    { item: "Corona", price: 5, itemQuantity: 1 },
    { item: "Bud", price: 5, itemQuantity: 1 },
    { item: "Ναργιλες Khalil", price: 7, itemQuantity: 1 },
    { item: "Ναργιλες Amy Deluxe", price: 10, itemQuantity: 1 },
    { item: "Ναργιλες Nube", price: 12, itemQuantity: 1 },
    { item: "Ναργιλες Alpha Hookah X", price: 15, itemQuantity: 1 },
    { item: "Ναργιλες Premium Hookah", price: 17, itemQuantity: 1 },
    { item: "Ναργιλες The Dark Side", price: 20, itemQuantity: 1 },
    { item: "El Dorado 3 y.o.", price: 7, itemQuantity: 1 },
    { item: "El Dorado 5 y.o.", price: 7, itemQuantity: 1 },
    { item: "Matusalem Anejo", price: 8, itemQuantity: 1 },
    { item: "Matusalem Reserva 15 y.o.", price: 11, itemQuantity: 1 },
    { item: "William Peel", price: 7, itemQuantity: 1 },
    { item: "Haig", price: 7, itemQuantity: 1 },
    { item: "Chivas 12 y.o.", price: 8, itemQuantity: 1 },
    { item: "The Irishman Founders Reserve", price: 10, itemQuantity: 1 },
    { item: "Jameson", price: 7, itemQuantity: 1 },
    { item: "Tullamore Dew", price: 7, itemQuantity: 1 },
    { item: "Michters US*1 Sour Mash", price: 12, itemQuantity: 1 },
    { item: "Buffalo Trace", price: 7, itemQuantity: 1 },
    { item: "The Glenlivet", price: 9, itemQuantity: 1 },
    { item: "Talisker 10 y.o", price: 10, itemQuantity: 1 },
    { item: "Jack Daniel", price: 7, itemQuantity: 1 },
    { item: "Giro", price: 7, itemQuantity: 1 },
    { item: "Portibello Road", price: 8, itemQuantity: 1 },
    { item: "Beefeater", price: 7, itemQuantity: 1 },
    { item: "Tanqueray", price: 7, itemQuantity: 1 },
    { item: "Hendricks", price: 11, itemQuantity: 1 },
    { item: "The Botanist", price: 9, itemQuantity: 1 },
    { item: "Poliakov Premium", price: 7, itemQuantity: 1 },
    { item: "Belvedere", price: 11, itemQuantity: 1 },
    { item: "Cimarron Blanco", price: 7.5, itemQuantity: 1 },
    { item: "Cimarron Resposado", price: 7.5, itemQuantity: 1 },
    { item: "Bruxo X", price: 10, itemQuantity: 1 },
    { item: "Spill the Tea", price: 8, itemQuantity: 1 },
    { item: "Smoking Dead", price: 8, itemQuantity: 1 },
    { item: "HOOKah-Up", price: 9, itemQuantity: 1 },
    { item: "Daybreak", price: 8, itemQuantity: 1 },
    { item: "Bloody-Loma", price: 8, itemQuantity: 1 },
    { item: "Colada Banana", price: 9, itemQuantity: 1 },
    { item: "Mermaids Mule", price: 8, itemQuantity: 1 },
    { item: "Messed Up", price: 8, itemQuantity: 1 },
    { item: "Im Not Old", price: 9, itemQuantity: 1 },
    { item: "Pink Apperitivo", price: 7, itemQuantity: 1 },
    { item: "Spiritz Veleziano", price: 7.5, itemQuantity: 1 },
    { item: "Monte & Tonic", price: 7, itemQuantity: 1 },
    { item: "Lets Get Physical", price: 7.5, itemQuantity: 1 },
  ];

